name: ai-composiso - Build and Push Docker Image
run-name: ${{ github.actor }} - ai-composiso - Build and Push Docker Image 🚀
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          cd ai-web-demo
          npm i

      - name: Build frontend
        run: |
          cd ai-web-demo
          npm run build

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/ai-composiso-frontend:${{ github.sha }} -f ai-web-demo/Dockerfile ./ai-web-demo

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image to GitHub Container Registry
        run: |
          echo ${{ secrets.PAT_TOKEN }}
          docker push ghcr.io/${{ github.actor }}/ai-composiso-frontend:${{ github.sha }}
